@startuml
title Brang - Admin (Use Case Diagram)
!define LIGHTBLUE
' !include style.puml
skinparam monochrome true

actor User <<Human>>

rectangle admin.py {
User --> (Add new Site)
(Add new Site) .down.> (Backend: Check if new \nSite URL is "valid") : <<include>>
User --> (Remove Site)
User --> (List Sites)
}
@enduml

@startuml
skinparam monochrome true

title Brang - Backend (Use Case Diagram)
actor Cron <<Machine>>
rectangle Server {
    Cron -->  (Check all Sites for Changes)
    (Update SiteChange DB Table \n if a change has been detected) .> (Check all Sites for Changes) : extends
    (Send Notification E-Mail) .up.> (Update SiteChange DB Table \n if a change has been detected) : extends
}
@enduml